In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
ROOT = r'C:\\Users\\an_em\\LocalDrive\\Projects\\arvadasermons'
os.chdir(ROOT)

In [9]:
from lib.load_data import load_data

In [17]:
idx = df['series']=='bonus episode'
df[idx]
df[~idx]

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
1,2026-04-08,2026,Bonus Episode | The 12 Steps,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/5._...,40774430,94476,general,None,2,bonus episode,The 12 Steps,None,None
24,2025-11-07,2025,BONUS EPISODE | The E Word | Jay & Tom,http://milehighvineyard.libsyn.com/bonus_the_e...,http://traffic.libsyn.com/milehighvineyard/Bon...,39016090,94476,general,BONUS EPISODE | The E Word | Jay & Tom,3,bonus episode,The E Word | Jay & Tom,None,None
36,2025-08-22,2025,BONUS EPISODE | Encountering the Kingdom | Jay...,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/3._...,37886695,94476,general,Check out Jay and Tom's latest bonus episode o...,3,bonus episode,Encountering the Kingdom | Jay & Tom,None,None
40,2025-08-01,2025,BONUS EPISODE | Job | Jay & Tom,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/2._...,37594145,94476,general,Jay and Tom finish out our series on Job with ...,3,bonus episode,Job | Jay & Tom,None,None
45,2025-07-04,2025,BONUS EPISODE | Where Did They All Go? | Jay a...,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/BON...,37263910,94476,general,Jay and Tom discuss the last sermon series loo...,3,bonus episode,Where Did They All Go? | Jay and Tom,None,None

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
0,2026-04-12,2026,Restored | Step 8 | Tom White | Mile High Vine...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40921040,94476,general,Restored | Step 8 | Tom White | Mile High Vine...,4,restored,Step 8,Tom White,Mile High Vineyard
2,2026-04-05,2026,Restored | Step 7 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40803880,94476,general,Restored | Step 7 | Jay Pathak | Mile High Vin...,4,restored,Step 7,Jay Pathak,Mile High Vineyard
3,2026-03-29,2026,Restored | Step 6 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40732005,94476,general,Restored | Step 6 | Jay Pathak | Mile High Vin...,4,restored,Step 6,Jay Pathak,Mile High Vineyard
4,2026-03-22,2026,Restored | Step 4 | Ben Folman | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40638395,94476,general,None,4,restored,Step 4,Ben Folman,Mile High Vineyard
5,2026-03-15,2026,Restored | Step 5 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40638505,94476,general,None,4,restored,Step 5,Jay Pathak,Mile High Vineyard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2022-06-26,2022,Anchor Week 7: God the Holy Spirit (Lord's Day...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-2...,23579204,94476,general,By Corey Garris,1,anchor week 7: god the holy spirit (lord's day...,None,None,None
194,2022-06-19,2022,Anchor Week 6: God the Son (Lord's Days 11-19),http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-1...,23541593,94476,general,By Corey Garris,1,anchor week 6: god the son (lord's days 11-19),None,None,None
195,2022-06-12,2022,Anchor Week 5: The Trinity & God the Father (L...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-1...,23541662,94476,general,By Jay Pathak,1,anchor week 5: the trinity & god the father (l...,None,None,None
196,2022-06-05,2022,Anchor Week 4: Man's Deliverance (Lord's Days ...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-6...,23367785,94476,general,By Corey Garris,1,anchor week 4: man's deliverance (lord's days ...,None,None,None
197,2022-05-29,2022,Anchor: Week 3 - Man's Sin & Misery (Lord's Da...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/5-2...,23367752,94476,general,By Jay Pathak,1,anchor: week 3 - man's sin & misery (lord's da...,None,None,None

In [12]:
df = load_data()
df.columns
df

Index(['date', 'year', 'title', 'episode_page', 'audio_url', 'episode_id',
       'dest_id', 'category', 'description', 'title_n_splits', 'series',
       'episode_label', 'speaker', 'church'],
      dtype='object')

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
0,2026-04-12,2026,Restored | Step 8 | Tom White | Mile High Vine...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40921040,94476,general,Restored | Step 8 | Tom White | Mile High Vine...,4,restored,Step 8,Tom White,Mile High Vineyard
1,2026-04-08,2026,Bonus Episode | The 12 Steps,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/5._...,40774430,94476,general,None,2,bonus episode,The 12 Steps,None,None
2,2026-04-05,2026,Restored | Step 7 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40803880,94476,general,Restored | Step 7 | Jay Pathak | Mile High Vin...,4,restored,Step 7,Jay Pathak,Mile High Vineyard
3,2026-03-29,2026,Restored | Step 6 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40732005,94476,general,Restored | Step 6 | Jay Pathak | Mile High Vin...,4,restored,Step 6,Jay Pathak,Mile High Vineyard
4,2026-03-22,2026,Restored | Step 4 | Ben Folman | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40638395,94476,general,None,4,restored,Step 4,Ben Folman,Mile High Vineyard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2022-06-26,2022,Anchor Week 7: God the Holy Spirit (Lord's Day...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-2...,23579204,94476,general,By Corey Garris,1,anchor week 7: god the holy spirit (lord's day...,None,None,None
194,2022-06-19,2022,Anchor Week 6: God the Son (Lord's Days 11-19),http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-1...,23541593,94476,general,By Corey Garris,1,anchor week 6: god the son (lord's days 11-19),None,None,None
195,2022-06-12,2022,Anchor Week 5: The Trinity & God the Father (L...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-1...,23541662,94476,general,By Jay Pathak,1,anchor week 5: the trinity & god the father (l...,None,None,None
196,2022-06-05,2022,Anchor Week 4: Man's Deliverance (Lord's Days ...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-6...,23367785,94476,general,By Corey Garris,1,anchor week 4: man's deliverance (lord's days ...,None,None,None
197,2022-05-29,2022,Anchor: Week 3 - Man's Sin & Misery (Lord's Da...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/5-2...,23367752,94476,general,By Jay Pathak,1,anchor: week 3 - man's sin & misery (lord's da...,None,None,None

In [15]:
for n_splits in df['title_n_splits'].unique():
    df[df.title_n_splits==n_splits]

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
0,2026-04-12,2026,Restored | Step 8 | Tom White | Mile High Vine...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40921040,94476,general,Restored | Step 8 | Tom White | Mile High Vine...,4,restored,Step 8,Tom White,Mile High Vineyard
2,2026-04-05,2026,Restored | Step 7 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40803880,94476,general,Restored | Step 7 | Jay Pathak | Mile High Vin...,4,restored,Step 7,Jay Pathak,Mile High Vineyard
3,2026-03-29,2026,Restored | Step 6 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40732005,94476,general,Restored | Step 6 | Jay Pathak | Mile High Vin...,4,restored,Step 6,Jay Pathak,Mile High Vineyard
4,2026-03-22,2026,Restored | Step 4 | Ben Folman | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40638395,94476,general,None,4,restored,Step 4,Ben Folman,Mile High Vineyard
5,2026-03-15,2026,Restored | Step 5 | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/restored-st...,http://traffic.libsyn.com/milehighvineyard/Res...,40638505,94476,general,None,4,restored,Step 5,Jay Pathak,Mile High Vineyard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2024-08-11,2024,Family Mess 11 | Genesis 28:10-22 | Jay Pathak...,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/8.1...,33520177,94476,general,None,4,family mess,Genesis 28:10-22,Jay Pathak,Mile High Vineyard
88,2024-08-04,2024,Family Mess 10 | Genesis 26:1-33 | Tom White |...,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/8.4...,33235902,94476,general,Family Mess 10 | Genesis 26:1-33 | Tom White |...,4,family mess,Genesis 26:1-33,Tom White,Mile High Vineyard
89,2024-07-28,2024,Family Mess 9 | Genesis 23 & 25:1-11 | Jay Pat...,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/7.2...,33226092,94476,Sermon,Family Mess 9 | Genesis 23 & 25:1-11 | Jay Pat...,4,family mess,Genesis 23 & 25:1-11,Jay Pathak,Mile High Vineyard
90,2024-07-21,2024,Family Mess 8 | Genesis 22:1-19 | Jay Pathak |...,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/7.2...,33225802,94476,general,Family Mess 8 | Genesis 22:1-19 | Jay Pathak |...,4,family mess,Genesis 22:1-19,Jay Pathak,Mile High Vineyard
99,2024-05-19,2024,Mealtime With Jesus 7 | Enacted Promise | Tom ...,http://milehighvineyard.libsyn.com/mealtime-wi...,http://traffic.libsyn.com/milehighvineyard/5-1...,31600102,94476,general,Mealtime With Jesus 7 | Enacted Promise | Tom ...,4,mealtime with jesus,Enacted Promise,Tom White,Mile High Vineyard

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
1,2026-04-08,2026,Bonus Episode | The 12 Steps,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/5._...,40774430,94476,general,None,2,bonus episode,The 12 Steps,None,None

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
24,2025-11-07,2025,BONUS EPISODE | The E Word | Jay & Tom,http://milehighvineyard.libsyn.com/bonus_the_e...,http://traffic.libsyn.com/milehighvineyard/Bon...,39016090,94476,general,BONUS EPISODE | The E Word | Jay & Tom,3,bonus episode,The E Word | Jay & Tom,None,None
32,2025-09-14,2025,The E Word: 2 | Becca Knudsen | Mile High Vine...,http://milehighvineyard.libsyn.com/the-e-word-...,http://traffic.libsyn.com/milehighvineyard/9.1...,38232410,94476,general,The E Word: 2 | Becca Knudsen | Mile High Vine...,3,the e word:,Becca Knudsen | Mile High Vineyard,None,None
33,2025-09-07,2025,The E Word: 1 | Jay Pathak | Mile High Vineyard,http://milehighvineyard.libsyn.com/the-e-word-...,http://traffic.libsyn.com/milehighvineyard/9.7...,38137320,94476,general,The E Word: 1 | Jay Pathak | Mile High Vineyard,3,the e word:,Jay Pathak | Mile High Vineyard,None,None
34,2025-08-31,2025,No One is Left Out | Jay Pathak | Mile High Vi...,http://milehighvineyard.libsyn.com/no-one-is-l...,http://traffic.libsyn.com/milehighvineyard/8.3...,38067205,94476,general,No One is Left Out | Jay Pathak | Mile High Vi...,3,no one is left out,Jay Pathak | Mile High Vineyard,None,None
35,2025-08-24,2025,Encountering the Kingdom 4 | Tom White | Mile ...,http://milehighvineyard.libsyn.com/encounterin...,http://traffic.libsyn.com/milehighvineyard/8.2...,37956420,94476,general,Encountering the Kingdom 4 | Tom White | Mile ...,3,encountering the kingdom,Tom White | Mile High Vineyard,None,None
36,2025-08-22,2025,BONUS EPISODE | Encountering the Kingdom | Jay...,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/3._...,37886695,94476,general,Check out Jay and Tom's latest bonus episode o...,3,bonus episode,Encountering the Kingdom | Jay & Tom,None,None
37,2025-08-17,2025,Encountering the Kingdom 3 | Jay Pathak | Mile...,http://milehighvineyard.libsyn.com/encounterin...,http://traffic.libsyn.com/milehighvineyard/8.1...,37871430,94476,general,Encountering the Kingdom 3 | Jay Pathak | Mile...,3,encountering the kingdom,Jay Pathak | Mile High Vineyard,None,None
38,2025-08-10,2025,Encountering the Kingdom 2 | Becca Knudsen | M...,http://milehighvineyard.libsyn.com/encounterin...,http://traffic.libsyn.com/milehighvineyard/8.1...,37770710,94476,general,Encountering the Kingdom 2 | Becca Knudsen | M...,3,encountering the kingdom,Becca Knudsen | Mile High Vineyard,None,None
39,2025-08-03,2025,Encountering the Kingdom | Anabeth Morgan | Mi...,http://milehighvineyard.libsyn.com/encounterin...,http://traffic.libsyn.com/milehighvineyard/8.3...,37686515,94476,general,Encountering the Kingdom | Anabeth Morgan | Mi...,3,encountering the kingdom,Anabeth Morgan | Mile High Vineyard,None,None
40,2025-08-01,2025,BONUS EPISODE | Job | Jay & Tom,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/2._...,37594145,94476,general,Jay and Tom finish out our series on Job with ...,3,bonus episode,Job | Jay & Tom,None,None
45,2025-07-04,2025,BONUS EPISODE | Where Did They All Go? | Jay a...,http://milehighvineyard.libsyn.com/bonus-episo...,http://traffic.libsyn.com/milehighvineyard/BON...,37263910,94476,general,Jay and Tom discuss the last sermon series loo...,3,bonus episode,Where Did They All Go? | Jay and Tom,None,None
46,2025-06-29,2025,Where Did They All Go? 10 | Jay Pathak | Mile ...,http://milehighvineyard.libsyn.com/where-did-t...,http://traffic.libsyn.com/milehighvineyard/6.2...,37247905,94476,general,Where Did They All Go? 10 | Jay Pathak | Mile ...,3,where did they all go?,Jay Pathak | Mile High Vineyard,None,None
67,2025-01-26,2025,Modern Day Psalms 2 | Tom White | Mile High Vi...,http://milehighvineyard.libsyn.com/modern-day-...,http://traffic.libsyn.com/milehighvineyard/1.2...,35052295,94476,general,Modern Day Psalms 2 | Tom White | Mile High Vi...,3,modern day psalms,Tom White | Mile High Vineyard,None,None
70,2025-01-05,2025,Sunday Service | Jay Pathak | Mile High Vineyard,http://milehighvineyard.libsyn.com/sunday-serv...,http://traffic.libsyn.com/milehighvineyard/1.5...,34760940,94476,general,Sunday Service | Jay Pathak | Mile High Vineyard,3,sunday service,Jay Pathak | Mile High Vineyard,None,None
71,2024-12-29,2024,New Years Service | Jay Pathak | Mile High Vin...,http://milehighvineyard.libsyn.com/new-years-s...,http://traffic.libsyn.com/milehighvineyard/12....,34715465,94476,general,New Years Service | Jay Pathak | Mile High Vin...,3,new years service,Jay Pathak | Mile High Vineyard,None,None
83,2024-09-22,2024,The Eyes We Need | Philippians 2:14-16 & 1 Cor...,http://milehighvineyard.libsyn.com/the-eyes-we...,http://traffic.libsyn.com/milehighvineyard/9.2...,33210447,94476,general,The Eyes We Need | Philippians 2:14-16 & 1 Cor...,3,the eyes we need,Philippians 2:14-16 & 1 Corinthians 9:19-23 | ...,None,None
91,2024-07-14,2024,Family Mess 7 | Genesis 20:1-18 | Tom White,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/7-1...,32141787,94476,general,Family Mess 7 | Genesis 20:1-18 | Tom White,3,family mess,Genesis 20:1-18 | Tom White,None,None
92,2024-07-07,2024,Family Mess 6 | Genesis 15:1-21 | Jay Pathak,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/7-7...,32141677,94476,general,Family Mess 6 | Genesis 15:1-21 | Jay Pathak,3,family mess,Genesis 15:1-21 | Jay Pathak,None,None
93,2024-06-30,2024,Family Mess 5 | Genesis 12:1-4 | Anabeth Morgan,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/6-3...,32141517,94476,general,Family Mess 5 | Genesis 12:1-4 | Anabeth Morgan,3,family mess,Genesis 12:1-4 | Anabeth Morgan,None,None
94,2024-06-23,2024,Family Mess 4 | Genesis 11 | Jay Pathak,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/6-2...,32141412,94476,general,Family Mess 4 | Genesis 11 | Jay Pathak,3,family mess,Genesis 11 | Jay Pathak,None,None
95,2024-06-16,2024,Family Mess 3 | Genesis 3 | Kirk Yamaguchi,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/6-1...,32141187,94476,general,Family Mess 3 | Genesis 3 | Kirk Yamaguchi,3,family mess,Genesis 3 | Kirk Yamaguchi,None,None
96,2024-06-09,2024,Family Mess 2 | Genesis 2 | Tom White,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/6-9...,32141072,94476,general,Family Mess 2 | Genesis 2 | Tom White,3,family mess,Genesis 2 | Tom White,None,None
97,2024-06-04,2024,Family Mess 1 | Genesis 1 | Becca Knudsen,http://milehighvineyard.libsyn.com/family-mess...,http://traffic.libsyn.com/milehighvineyard/6-2...,31600337,94476,general,Family Mess 1 | Genesis 1 | Becca Knudsen | Mi...,3,family mess,Genesis 1 | Becca Knudsen,None,None
98,2024-05-26,2024,Serving In A Church | Jay Pathak | Mile High V...,http://milehighvineyard.libsyn.com/serving-in-...,http://traffic.libsyn.com/milehighvineyard/5-2...,31600202,94476,general,Serving In A Church | Jay Pathak | Mile High V...,3,serving in a church,Jay Pathak | Mile High Vineyard,None,None
100,2024-05-12,2024,Mealtime With Jesus | Enacted Salvation | Joel...,http://milehighvineyard.libsyn.com/mealtime-wi...,http://traffic.libsyn.com/milehighvineyard/5-1...,31249767,94476,general,Mealtime With Jesus | Enacted Salvation | Joel...,3,mealtime with jesus,Enacted Salvation | Joel Seymour,None,None
101,2024-05-05,2024,Mealtime With Jesus | Enacted Mission | Anabet...,http://milehighvineyard.libsyn.com/mealtime-wi...,http://traffic.libsyn.com/milehighvineyard/5-5...,31249757,94476,general,Mealtime With Jesus | Enacted Mission | Anabet...,3,mealtime with jesus,Enacted Mission | Anabeth Morgan,None,None
102,2024-04-28,2024,Mealtime With Jesus | Enacted Hope | Tom White,http://milehighvineyard.libsyn.com/mealtime-wi...,http://traffic.libsyn.com/milehighvineyard/4-2...,31249742,94476,general,Mealtime With Jesus | Enacted Hope | Tom White,3,mealtime with jesus,Enacted Hope | Tom White,None,None
103,2024-04-21,2024,Mealtime With Jesus | Enacted Community | Ryan...,http://milehighvineyard.libsyn.com/mealtime-wi...,http://traffic.libsyn.com/milehighvineyard/4-2...,31249727,94476,general,Mealtime With Jesus | Enacted Community | Ryan...,3,mealtime with jesus,Enacted Community | Ryan Rowlette,None,None
104,2024-04-14,2024,Mealtime With Jesus | Enacted Grace | Jay Pathak,http://milehighvineyard.libsyn.com/mealtime-wi...,http://traffic.libsyn.com/milehighvineyard/4-1...,31249712,94476,general,Mealtime With Jesus | Enacted Grace | Jay Pathak,3,mealtime with jesus,Enacted Grace | Jay Pathak,None,None
105,2024-04-07,2024,Mealtime With Jesus | Jesus and Meals | Tom White,http://milehighvineyard.libsyn.com/mealtime-wi...,http://traffic.libsyn.com/milehighvineyard/4-7...,31249682,94476,general,Mealtime With Jesus | Jesus and Meals | Tom White,3,mealtime with jesus,Jesus and Meals | Tom White,None,None
106,2024-03-31,2024,Easter Service 2024 | Jay Pathak | Mile High V...,http://milehighvineyard.libsyn.com/easter-serv...,http://traffic.libsyn.com/milehighvineyard/3-3...,31249642,94476,general,Easter Service 2024 | Jay Pathak | Mile High V...,3,easter service,Jay Pathak | Mile High Vineyard,None,None
107,2024-03-24,2024,LENT 2024 | John 8 | Tom White,http://milehighvineyard.libsyn.com/lent-2024-j...,http://traffic.libsyn.com/milehighvineyard/3-2...,31249632,94476,general,LENT 2024 | John 8 | Tom White,3,lent,John 8 | Tom White,None,None
108,2024-03-17,2024,LENT 2024 | John 6 | Todd Bryski,http://milehighvineyard.libsyn.com/lent-2024-j...,http://traffic.libsyn.com/milehighvineyard/3-1...,31249622,94476,general,LENT 2024 | John 6 | Todd Bryski,3,lent,John 6 | Todd Bryski,None,None
109,2024-03-10,2024,LENT 2024 | John 5 | Ryan Rowlette,http://milehighvineyard.libsyn.com/lent-2024-j...,http://traffic.libsyn.com/milehighvineyard/3-1...,31249617,94476,general,LENT 2024 | John 5 | Ryan Rowlette,3,lent,John 5 | Ryan Rowlette,None,None
110,2024-03-03,2024,LENT 2024 | John 4 | Jay Pathak,http://milehighvineyard.libsyn.com/lent-2024-j...,http://traffic.libsyn.com/milehighvineyard/3-3...,31249597,94476,general,None,3,lent,John 4 | Jay Pathak,None,None
111,2024-02-25,2024,LENT 2024 | John 3 | Anabeth Morgan,http://milehighvineyard.libsyn.com/lent-2024-j...,http://traffic.libsyn.com/milehighvineyard/2-2...,31249607,94476,general,LENT 2024 | John 3 | Anabeth Morgan,3,lent,John 3 | Anabeth Morgan,None,None
112,2024-02-18,2024,LENT 2024 | John 2 | Jay Pathak,http://milehighvineyard.libsyn.com/lent-2024-j...,http://traffic.libsyn.com/milehighvineyard/2-1...,30017073,94476,general,LENT 2024 | John 2 | Jay Pathak,3,lent,John 2 | Jay Pathak,None,None
113,2024-02-04,2024,Reset | Living for the Lost | Jay Pathak,http://milehighvineyard.libsyn.com/reset-livin...,http://traffic.libsyn.com/milehighvineyard/2-4...,30016943,94476,general,Reset | Living for the Lost | Jay Pathak,3,reset,Living for the Lost | Jay Pathak,None,None
114,2024-01-28,2024,Reset | Kingdom Of God | Jay Pathak,http://milehighvineyard.libsyn.com/reset-kingd...,http://traffic.libsyn.com/milehighvineyard/1-2...,30016878,94476,general,Reset | Kingdom Of God | Jay Pathak,3,reset,Kingdom Of God | Jay Pathak,None,None
115,2024-01-21,2024,Reset | Collaboration | Tom White,http://milehighvineyard.libsyn.com/reset-colla...,http://traffic.libsyn.com/milehighvineyard/1-2...,30016758,94476,general,Reset | Collaboration | Tom White,3,reset,Collaboration | Tom White,None,None
116,2024-01-14,2024,Reset | Personal Responsibility | Corey Garris,http://milehighvineyard.libsyn.com/reset-perso...,http://traffic.libsyn.com/milehighvineyard/1-1...,29514483,94476,general,Reset | Personal Responsibility | Corey Garris,3,reset,Personal Responsibility | Corey Garris,None,None
117,2024-01-07,2024,Reset | MHV Values | Jay Pathak,http://milehighvineyard.libsyn.com/reset-mhv-v...,http://traffic.libsyn.com/milehighvineyard/1-7...,29514458,94476,general,Reset | MHV Values | Jay Pathak,3,reset,MHV Values | Jay Pathak,None,None
118,2023-12-17,2023,Advent 2023 | John The Baptist | Brittany Kurtz,http://milehighvineyard.libsyn.com/advent-2023...,http://traffic.libsyn.com/milehighvineyard/12-...,29514403,94476,general,Advent 2023 | John The Baptist | Brittany Kurtz,3,advent,John The Baptist | Brittany Kurtz,None,None
119,2023-12-10,2023,Advent 2023 | Waiting & Longing | Corey Garris,http://milehighvineyard.libsyn.com/advent-2023...,http://traffic.libsyn.com/milehighvineyard/12-...,29514393,94476,general,Advent 2023 | Waiting & Longing | Corey Garris,3,advent,Waiting & Longing | Corey Garris,None,None
120,2023-12-03,2023,Advent 2023 | Chronos & Kairos Time | Jay Pathak,http://milehighvineyard.libsyn.com/advent-2023...,http://traffic.libsyn.com/milehighvineyard/12-...,29514373,94476,general,Advent 2023 | Chronos & Kairos Time | Jay Pathak,3,advent,Chronos & Kairos Time | Jay Pathak,None,None
121,2023-11-26,2023,Don't Die Dumb | Finding Wisdom | Corey Garris,http://milehighvineyard.libsyn.com/dont-die-du...,http://traffic.libsyn.com/milehighvineyard/11-...,29514203,94476,general,Don't Die Dumb | Finding Wisdom | Corey Garris,3,don't die dumb,Finding Wisdom | Corey Garris,None,None
122,2023-11-19,2023,Don't Die Dumb | Generosity | Anabeth Morgan,http://milehighvineyard.libsyn.com/dont-die-du...,http://traffic.libsyn.com/milehighvineyard/11-...,28740433,94476,general,Don't Die Dumb | Generosity | Anabeth Morgan,3,don't die dumb,Generosity | Anabeth Morgan,None,None
123,2023-11-12,2023,Don't Die Dumb | Offense | Corey Garris,http://milehighvineyard.libsyn.com/dont-die-du...,http://traffic.libsyn.com/milehighvineyard/11-...,28709378,94476,general,Don't Die Dumb | Offense | Corey Garris,3,don't die dumb,Offense | Corey Garris,None,None
124,2023-11-05,2023,Don't Die Dumb | Grey Hair | David Parker,http://milehighvineyard.libsyn.com/dont-die-du...,http://traffic.libsyn.com/milehighvineyard/11-...,28709263,94476,general,Don't Die Dumb | Grey Hair | David Parker,3,don't die dumb,Grey Hair | David Parker,None,None
125,2023-10-29,2023,Don't Die Dumb | Quick Fixes | Jay Pathak,http://milehighvineyard.libsyn.com/dont-die-du...,http://traffic.libsyn.com/milehighvineyard/10-...,28709308,94476,general,Don't Die Dumb | Qucik Fixes | Jay Pathak,3,don't die dumb,Quick Fixes | Jay Pathak,None,None

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
30,2025-09-28,2025,the e word | 4 | Acts 8:26–40 | Jay Pathak | M...,http://milehighvineyard.libsyn.com/the-e-word-...,http://traffic.libsyn.com/milehighvineyard/9.2...,38401065,94476,general,the e word | 4 | Acts 8:26–40 | Jay Pathak | M...,5,the e word,4 | Acts 8:26–40,Jay Pathak,Mile High Vineyard
31,2025-09-21,2025,the e word | 3 | John 9:13–34 | Jay Pathak | M...,http://milehighvineyard.libsyn.com/the-e-word-...,http://traffic.libsyn.com/milehighvineyard/9.2...,38319720,94476,general,the e word | 3 | John 9:13–34 | Jay Pathak | M...,5,the e word,3 | John 9:13–34,Jay Pathak,Mile High Vineyard

,date,year,title,episode_page,audio_url,episode_id,dest_id,category,description,title_n_splits,series,episode_label,speaker,church
126,2023-10-22,2023,I Pledge Allegiance: Week 7 By Corey Garris,http://milehighvineyard.libsyn.com/i-pledge-al...,http://traffic.libsyn.com/milehighvineyard/10-...,28709253,94476,general,I Pledge Allegiance: Week 7 By Corey Garris,1,i pledge allegiance: week 7 by corey garris,None,None,None
127,2023-10-15,2023,I Pledge Allegiance: Week 6 By Tom White,http://milehighvineyard.libsyn.com/i-pledge-al...,http://traffic.libsyn.com/milehighvineyard/10-...,28709193,94476,general,I Pledge Allegiance: Week 6 By Tom White,1,i pledge allegiance: week 6 by tom white,None,None,None
128,2023-10-08,2023,I Pledge Allegiance: Week 5 By Corey Garris,http://milehighvineyard.libsyn.com/i-pledge-al...,http://traffic.libsyn.com/milehighvineyard/10-...,28709173,94476,general,I Pledge Allegiance: Week 5 By Corey Garris,1,i pledge allegiance: week 5 by corey garris,None,None,None
129,2023-10-01,2023,I Pledge Allegiance: Week 4 By Jay Pathak,http://milehighvineyard.libsyn.com/i-pledge-al...,http://traffic.libsyn.com/milehighvineyard/10-...,28256477,94476,general,I Pledge Allegiance: Week 4 By Jay Pathak,1,i pledge allegiance: week 4 by jay pathak,None,None,None
130,2023-09-24,2023,I Pledge Allegiance: Week 3 By Corey Garris,http://milehighvineyard.libsyn.com/i-pledge-al...,http://traffic.libsyn.com/milehighvineyard/9-2...,28256468,94476,general,I Pledge Allegiance: Week 3 By Corey Garris,1,i pledge allegiance: week 3 by corey garris,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2022-06-26,2022,Anchor Week 7: God the Holy Spirit (Lord's Day...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-2...,23579204,94476,general,By Corey Garris,1,anchor week 7: god the holy spirit (lord's day...,None,None,None
194,2022-06-19,2022,Anchor Week 6: God the Son (Lord's Days 11-19),http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-1...,23541593,94476,general,By Corey Garris,1,anchor week 6: god the son (lord's days 11-19),None,None,None
195,2022-06-12,2022,Anchor Week 5: The Trinity & God the Father (L...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-1...,23541662,94476,general,By Jay Pathak,1,anchor week 5: the trinity & god the father (l...,None,None,None
196,2022-06-05,2022,Anchor Week 4: Man's Deliverance (Lord's Days ...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/6-6...,23367785,94476,general,By Corey Garris,1,anchor week 4: man's deliverance (lord's days ...,None,None,None
197,2022-05-29,2022,Anchor: Week 3 - Man's Sin & Misery (Lord's Da...,http://milehighvineyard.libsyn.com/anchor-week...,http://traffic.libsyn.com/milehighvineyard/5-2...,23367752,94476,general,By Jay Pathak,1,anchor: week 3 - man's sin & misery (lord's da...,None,None,None